name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "10 23 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          THEME_NAME: radical

      - name: Update Streak Stats Cache Buster
        run: |
          TIMESTAMP=$(date +%s)
          sed -i -E "s|(https://streak-stats\.demolab\.com\?[^ \)]*)|\1\&date=$TIMESTAMP|g" README.md
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update cache buster for streak stats" || echo "No changes to commit"
          git push

      - name: Purge Camo Cache
        uses: wow-actions/purge-readme@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
